There will be more going through the motions here. Taking the quadratic formula example:

In [1]:
coef_a <- 1
coef_b <- 1
# Named to avoid conflict with builtin function c()
coef_c <- -1

Very basic printing, which I won't really use in the future because it's Jupyter:

In [2]:
print(coef_a)
print(coef_b)
print(coef_c)

[1] 1
[1] 1
[1] -1

Here's the equivalent of `dir()` (only shows user-defined variables by default):

In [3]:
ls()

[1] "coef_a" "coef_b" "coef_c"

I'm going to do one (or two) better than the book and use a function to calculate the two roots, in addition to making the discriminant a complex number:

In [4]:
quadratic_formula <- function(a, b, c) {
    discriminant <- sqrt(as.complex(b^2 - 4 * a * c))
    r_1 <- (-b - discriminant) / (2 * a)
    r_2 <- (-b + discriminant) / (2 * a)

    list(r_1, r_2)
}

In [5]:
quadratic_formula(coef_a, coef_b, coef_c)

[[1]]
[1] -1.618034+0i

[[2]]
[1] 0.618034+0i

The code above also works with imaginary roots:

In [6]:
quadratic_formula(coef_a, coef_b, 100)

[[1]]
[1] -0.5-9.987492i

[[2]]
[1] -0.5+9.987492i

The book goes into further detail about functions. Note that just evaluating `ls` for example without function application will reveal the source of said function:

In [7]:
ls

function (name, pos = -1L, envir = as.environment(pos), all.names = FALSE,
    pattern, sorted = TRUE)
{
    if (!missing(name)) {
        pos <- tryCatch(name, error = function(e) e)
        if (inherits(pos, "error")) {
            name <- substitute(name)
            if (!is.character(name))
                name <- deparse(name)
            warning(gettextf("%s converted to character string",
                sQuote(name)), domain = NA)
            pos <- name
        }
    }
    all.names <- .Internal(ls(envir, all.names, sorted))
    if (!missing(pattern)) {
        if ((ll <- length(grep("[", pattern, fixed = TRUE))) &&
            ll != length(grep("]", pattern, fixed = TRUE))) {
            if (pattern == "[") {
                pattern <- "\\["
                warning("replaced regular expression pattern '[' by  '\\\\['")
            }
            else if (length(grep("[^\\\\]\\[<-", pattern))) {
                pattern <- sub("\\[<-", "\\\\\\[<-", pattern)
                warning("replaced '[<-' by '\\\\[<-' in regular expression pattern")
            }
        }
        grep(pattern, all.names, value = TRUE)
    }
    else all.names
}
<bytecode: 0x555ead5ac7d0>
<environment: namespace:base>

The book covers some more basic info on functions using `log()`:

In [8]:
log(8)
log(coef_a)

[1] 2.079442

[1] 0

And now the help system:

In [9]:
help(log)

log                    package:base                    R Documentation

_L_o_g_a_r_i_t_h_m_s _a_n_d _E_x_p_o_n_e_n_t_i_a_l_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘log’ computes logarithms, by default natural logarithms, ‘log10’
     computes common (i.e., base 10) logarithms, and ‘log2’ computes
     binary (i.e., base 2) logarithms.  The general form ‘log(x, base)’
     computes logarithms with base ‘base’.

     ‘log1p(x)’ computes log(1+x) accurately also for |x| << 1.

     ‘exp’ computes the exponential function.

     ‘expm1(x)’ computes exp(x) - 1 accurately also for |x| << 1.

_U_s_a_g_e:

     log(x, base = exp(1))
     logb(x, base = exp(1))
     log10(x)
     log2(x)

     log1p(x)

     exp(x)
     expm1(x)

_A_r_g_u_m_e_n_t_s:

       x: a numeric or complex vector.

    base: a positive or complex number: the base with respect to which
          logarithms are computed.  Defaults to e=‘exp(1)’.

_D_e_t_a_i_l_s:

     All except ‘logb’ are generic functions: methods can be defined
     for them individually or via the ‘Math’ group generic.

     ‘log10’ and ‘log2’ are only convenience wrappers, but logs to
     bases 10 and 2 (whether computed _via_ ‘log’ or the wrappers) will
     be computed more efficiently and accurately where supported by the
     OS.  Methods can be set for them individually (and otherwise
     methods for ‘log’ will be used).

     ‘logb’ is a wrapper for ‘log’ for compatibility with S.  If (S3 or
     S4) methods are set for ‘log’ they will be dispatched.  Do not set
     S4 methods on ‘logb’ itself.

     All except ‘log’ are primitive functions.

_V_a_l_u_e:

     A vector of the same length as ‘x’ containing the transformed
     values.  ‘log(0)’ gives ‘-Inf’, and ‘log(x)’ for negative values
     of ‘x’ is ‘NaN’.  ‘exp(-Inf)’ is ‘0’.

     For complex inputs to the log functions, the value is a complex
     number with imaginary part in the range [-pi, pi]: which end of
     the range is used might be platform-specific.

_S_4 _m_e_t_h_o_d_s:

     ‘exp’, ‘expm1’, ‘log’, ‘log10’, ‘log2’ and ‘log1p’ are S4 generic
     and are members of the ‘Math’ group generic.

     Note that this means that the S4 generic for ‘log’ has a signature
     with only one argument, ‘x’, but that ‘base’ can be passed to
     methods (but will not be used for method selection).  On the other
     hand, if you only set a method for the ‘Math’ group generic then
     ‘base’ argument of ‘log’ will be ignored for your class.

_S_o_u_r_c_e:

     ‘log1p’ and ‘expm1’ may be taken from the operating system, but if
     not available there then they are based on the Fortran subroutine
     ‘dlnrel’ by W. Fullerton of Los Alamos Scientific Laboratory (see
     <https://netlib.org/slatec/fnlib/dlnrel.f>) and (for small x) a
     single Newton step for the solution of ‘log1p(y) = x’
     respectively.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.  (for ‘log’, ‘log10’ and
     ‘exp’.)

     Chambers, J. M. (1998) _Programming with Data.  A Guide to the S
     Language_.  Springer. (for ‘logb’.)

_S_e_e _A_l_s_o:

     ‘Trig’, ‘sqrt’, ‘Arithmetic’.

_E_x_a_m_p_l_e_s:

     log(exp(3))
     log10(1e7) # = 7

     x <- 10^-(1+2*1:9)
     cbind(deparse.level=2, # to get nice column names
           x, log(1+x), log1p(x), exp(x)-1, expm1(x))

Notice that `?` typically works as well:

In [10]:
?log

log                    package:base                    R Documentation

_L_o_g_a_r_i_t_h_m_s _a_n_d _E_x_p_o_n_e_n_t_i_a_l_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘log’ computes logarithms, by default natural logarithms, ‘log10’
     computes common (i.e., base 10) logarithms, and ‘log2’ computes
     binary (i.e., base 2) logarithms.  The general form ‘log(x, base)’
     computes logarithms with base ‘base’.

     ‘log1p(x)’ computes log(1+x) accurately also for |x| << 1.

     ‘exp’ computes the exponential function.

     ‘expm1(x)’ computes exp(x) - 1 accurately also for |x| << 1.

_U_s_a_g_e:

     log(x, base = exp(1))
     logb(x, base = exp(1))
     log10(x)
     log2(x)

     log1p(x)

     exp(x)
     expm1(x)

_A_r_g_u_m_e_n_t_s:

       x: a numeric or complex vector.

    base: a positive or complex number: the base with respect to which
          logarithms are computed.  Defaults to e=‘exp(1)’.

_D_e_t_a_i_l_s:

     All except ‘logb’ are generic functions: methods can be defined
     for them individually or via the ‘Math’ group generic.

     ‘log10’ and ‘log2’ are only convenience wrappers, but logs to
     bases 10 and 2 (whether computed _via_ ‘log’ or the wrappers) will
     be computed more efficiently and accurately where supported by the
     OS.  Methods can be set for them individually (and otherwise
     methods for ‘log’ will be used).

     ‘logb’ is a wrapper for ‘log’ for compatibility with S.  If (S3 or
     S4) methods are set for ‘log’ they will be dispatched.  Do not set
     S4 methods on ‘logb’ itself.

     All except ‘log’ are primitive functions.

_V_a_l_u_e:

     A vector of the same length as ‘x’ containing the transformed
     values.  ‘log(0)’ gives ‘-Inf’, and ‘log(x)’ for negative values
     of ‘x’ is ‘NaN’.  ‘exp(-Inf)’ is ‘0’.

     For complex inputs to the log functions, the value is a complex
     number with imaginary part in the range [-pi, pi]: which end of
     the range is used might be platform-specific.

_S_4 _m_e_t_h_o_d_s:

     ‘exp’, ‘expm1’, ‘log’, ‘log10’, ‘log2’ and ‘log1p’ are S4 generic
     and are members of the ‘Math’ group generic.

     Note that this means that the S4 generic for ‘log’ has a signature
     with only one argument, ‘x’, but that ‘base’ can be passed to
     methods (but will not be used for method selection).  On the other
     hand, if you only set a method for the ‘Math’ group generic then
     ‘base’ argument of ‘log’ will be ignored for your class.

_S_o_u_r_c_e:

     ‘log1p’ and ‘expm1’ may be taken from the operating system, but if
     not available there then they are based on the Fortran subroutine
     ‘dlnrel’ by W. Fullerton of Los Alamos Scientific Laboratory (see
     <https://netlib.org/slatec/fnlib/dlnrel.f>) and (for small x) a
     single Newton step for the solution of ‘log1p(y) = x’
     respectively.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.  (for ‘log’, ‘log10’ and
     ‘exp’.)

     Chambers, J. M. (1998) _Programming with Data.  A Guide to the S
     Language_.  Springer. (for ‘logb’.)

_S_e_e _A_l_s_o:

     ‘Trig’, ‘sqrt’, ‘Arithmetic’.

_E_x_a_m_p_l_e_s:

     log(exp(3))
     log10(1e7) # = 7

     x <- 10^-(1+2*1:9)
     cbind(deparse.level=2, # to get nice column names
           x, log(1+x), log1p(x), exp(x)-1, expm1(x))

The book covers `args()` as well, which I didn't know about previously:

In [11]:
args(log)

function (x, base = exp(1))
NULL

`log()` has an optional argument, `base`:

In [12]:
log(8, base=2)

[1] 3

Several other ways of specifying arguments with or without keywords are shown:

In [13]:
log(x = 8, base = 2)
log(8, 2)
# Here the order doesn't even matter because all keywords were specified
log(base = 2, x = 8)

[1] 3

[1] 3

[1] 3

There are exceptions to the rule that functions require parentheses to be evaluated. Among these are the arithmetic operators:

In [14]:
2^3

[1] 8

Note that these and a number of other operators are *indeed* functions:

In [15]:
`^`

function (e1, e2)  .Primitive("^")

The backticks can even be used to apply an operator like `^` as a prefix function like most other functions:

In [16]:
`^`(2, 3)

[1] 8

The book advises that quotes can be used to look up the help info on these operators:

In [17]:
help('^')

Arithmetic                package:base                 R Documentation

_A_r_i_t_h_m_e_t_i_c _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     These unary and binary operators perform arithmetic on numeric or
     complex vectors (or objects which can be coerced to them).

_U_s_a_g_e:

     + x
     - x
     x + y
     x - y
     x * y
     x / y
     x ^ y
     x %% y
     x %/% y

_A_r_g_u_m_e_n_t_s:

    x, y: numeric or complex vectors or objects which can be coerced to
          such, or other objects for which methods have been written.

_D_e_t_a_i_l_s:

     The unary and binary arithmetic operators are generic functions:
     methods can be written for them individually or via the ‘Ops’
     group generic function.  (See ‘Ops’ for how dispatch is computed.)

     If applied to arrays the result will be an array if this is
     sensible (for example it will not if the recycling rule has been
     invoked).

     Logical vectors will be coerced to integer or numeric vectors,
     ‘FALSE’ having value zero and ‘TRUE’ having value one.

     ‘1 ^ y’ and ‘y ^ 0’ are ‘1’, _always_.  ‘x ^ y’ should also give
     the proper limit result when either (numeric) argument is infinite
     (one of ‘Inf’ or ‘-Inf’).

     Objects such as arrays or time-series can be operated on this way
     provided they are conformable.

     For double arguments, ‘%%’ can be subject to catastrophic loss of
     accuracy if ‘x’ is much larger than ‘y’, and a warning is given if
     this is detected.

     ‘%%’ and ‘x %/% y’ can be used for non-integer ‘y’, e.g. ‘1 %/%
     0.2’, but the results are subject to representation error and so
     may be platform-dependent.  Mathematically, the answer to ‘1 %/%
     0.2’ should be ‘5’, but because the IEC 60559 representation of
     ‘0.2’ is a binary fraction slightly larger than ‘0.2’ most
     platforms give ‘4’.

     Users are sometimes surprised by the value returned, for example
     why ‘(-8)^(1/3)’ is ‘NaN’.  For double inputs, R makes use of IEC
     60559 arithmetic on all platforms, together with the C system
     function ‘pow’ for the ‘^’ operator.  The relevant standards
     define the result in many corner cases.  In particular, the result
     in the example above is mandated by the C99 standard.  On many
     Unix-alike systems the command ‘man pow’ gives details of the
     values in a large number of corner cases.

     Arithmetic on type double in R is supposed to be done in ‘round to
     nearest, ties to even’ mode, but this does depend on the compiler
     and FPU being set up correctly.

_V_a_l_u_e:

     Unary ‘+’ and unary ‘-’ return a numeric or complex vector.  All
     attributes (including class) are preserved if there is no
     coercion: logical ‘x’ is coerced to integer and names, dims and
     dimnames are preserved.

     The binary operators return vectors containing the result of the
     element by element operations.  If involving a zero-length vector
     the result has length zero.  Otherwise, the elements of shorter
     vectors are recycled as necessary (with a ‘warning’ when they are
     recycled only _fractionally_).  The operators are ‘+’ for
     addition, ‘-’ for subtraction, ‘*’ for multiplication, ‘/’ for
     division and ‘^’ for exponentiation.

     ‘%%’ indicates ‘x mod y’ (“x modulo y”), i.e., computes the
     ‘remainder’ ‘r <- x %% y’, and ‘%/%’ indicates integer division,
     where R uses “floored” integer division, i.e., ‘q <- x %/% y :=
     floor(x/y)’, as promoted by Donald Knuth, see the Wikipedia page
     on ‘Modulo operation’, and hence ‘sign(r) == sign(y)’.  It is
     guaranteed that

     ‘ x == (x %% y) + y * (x %/% y) ’ (up to rounding error)

     unless ‘y == 0’ where the result of ‘%%’ is ‘NA_integer_’ or ‘NaN’
     (depending on the ‘typeof’ of the arguments) or for some
     non-finite arguments, e.g., when the RHS of the identity above
     amounts to ‘Inf - Inf’.

     If either argument is complex the result will be complex,
     otherwise if one or both arguments are numeric, the result will be
     numeric.  If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).

     The rules for determining the attributes of the result are rather
     complicated.  Most attributes are taken from the longer argument.
     Names will be copied from the first if it is the same length as
     the answer, otherwise from the second if that is.  If the
     arguments are the same length, attributes will be copied from
     both, with those of the first argument taking precedence when the
     same attribute is present in both arguments. For time series,
     these operations are allowed only if the series are compatible,
     when the class and ‘tsp’ attribute of whichever is a time series
     (the same, if both are) are used.  For arrays (and an array
     result) the dimensions and dimnames are taken from first argument
     if it is an array, otherwise the second.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Arith’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’ (with ‘e2’ missing for a unary operator).

_I_m_p_l_e_m_e_n_t_a_t_i_o_n _l_i_m_i_t_s:

     R is dependent on OS services (and they on FPUs) for
     floating-point arithmetic.  On all current R platforms IEC 60559
     (also known as IEEE 754) arithmetic is used, but some things in
     those standards are optional.  In particular, the support for
     _denormal_ aka _subnormal_ numbers (those outside the range given
     by ‘.Machine’) may differ between platforms and even between
     calculations on a single platform.

     Another potential issue is signed zeroes: on IEC 60559 platforms
     there are two zeroes with internal representations differing by
     sign.  Where possible R treats them as the same, but for example
     direct output from C code often does not do so and may output
     ‘-0.0’ (and on Windows whether it does so or not depends on the
     version of Windows).  One place in R where the difference might be
     seen is in division by zero: ‘1/x’ is ‘Inf’ or ‘-Inf’ depending on
     the sign of zero ‘x’.  Another place is ‘identical(0, -0, num.eq =
     FALSE)’.

_N_o_t_e:

     All logical operations involving a zero-length vector have a
     zero-length result.

     The binary operators are sometimes called as functions as e.g.
     ‘`&`(x, y)’: see the description of how argument-matching is done
     in ‘Ops’.

     ‘**’ is translated in the parser to ‘^’, but this was undocumented
     for many years.  It appears as an index entry in Becker et al.
     (1988), pointing to the help for ‘Deprecated’ but is not actually
     mentioned on that page.  Even though it had been deprecated in S
     for 20 years, it was still accepted in R in 2008.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     D. Goldberg (1991).  What Every Computer Scientist Should Know
     about Floating-Point Arithmetic.  _ACM Computing Surveys_,
     *23*(1), 5-48.  doi:10.1145/103162.103163
     <https://doi.org/10.1145/103162.103163>.

     Also available at
     <https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html>.

     For the IEC 60559 (aka IEEE 754) standard:
     <https://www.iso.org/standard/57469.html> and
     <https://en.wikipedia.org/wiki/IEEE_754>.

     On the integer division and remainder (modulo) computations, ‘%%’
     and ‘%/%’: <https://en.wikipedia.org/wiki/Modulo_operation>, and
     Donald Knuth (1972) _The Art of Computer Programming_, Vol.1.

_S_e_e _A_l_s_o:

     ‘sqrt’ for miscellaneous and ‘Special’ for special mathematical
     functions.

     ‘Syntax’ for operator precedence.

     ‘%*%’ for matrix multiplication.

_E_x_a_m_p_l_e_s:

     x <- -1:12
     x + 1
     2 * x + 3
     x %%  3 # is periodic  2 0  1  2 0  1 ...
     x %% -3 #  (ditto)    -1 0 -2 -1 0 -2 ...
     x %/% 5
     x %% Inf # now is defined by limit (gave NaN in earlier versions of R)

     ## Illustrating PR#18677, see above
     1 %/% print(0.2, digits=19)

In [18]:
?'^'

Arithmetic                package:base                 R Documentation

_A_r_i_t_h_m_e_t_i_c _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     These unary and binary operators perform arithmetic on numeric or
     complex vectors (or objects which can be coerced to them).

_U_s_a_g_e:

     + x
     - x
     x + y
     x - y
     x * y
     x / y
     x ^ y
     x %% y
     x %/% y

_A_r_g_u_m_e_n_t_s:

    x, y: numeric or complex vectors or objects which can be coerced to
          such, or other objects for which methods have been written.

_D_e_t_a_i_l_s:

     The unary and binary arithmetic operators are generic functions:
     methods can be written for them individually or via the ‘Ops’
     group generic function.  (See ‘Ops’ for how dispatch is computed.)

     If applied to arrays the result will be an array if this is
     sensible (for example it will not if the recycling rule has been
     invoked).

     Logical vectors will be coerced to integer or numeric vectors,
     ‘FALSE’ having value zero and ‘TRUE’ having value one.

     ‘1 ^ y’ and ‘y ^ 0’ are ‘1’, _always_.  ‘x ^ y’ should also give
     the proper limit result when either (numeric) argument is infinite
     (one of ‘Inf’ or ‘-Inf’).

     Objects such as arrays or time-series can be operated on this way
     provided they are conformable.

     For double arguments, ‘%%’ can be subject to catastrophic loss of
     accuracy if ‘x’ is much larger than ‘y’, and a warning is given if
     this is detected.

     ‘%%’ and ‘x %/% y’ can be used for non-integer ‘y’, e.g. ‘1 %/%
     0.2’, but the results are subject to representation error and so
     may be platform-dependent.  Mathematically, the answer to ‘1 %/%
     0.2’ should be ‘5’, but because the IEC 60559 representation of
     ‘0.2’ is a binary fraction slightly larger than ‘0.2’ most
     platforms give ‘4’.

     Users are sometimes surprised by the value returned, for example
     why ‘(-8)^(1/3)’ is ‘NaN’.  For double inputs, R makes use of IEC
     60559 arithmetic on all platforms, together with the C system
     function ‘pow’ for the ‘^’ operator.  The relevant standards
     define the result in many corner cases.  In particular, the result
     in the example above is mandated by the C99 standard.  On many
     Unix-alike systems the command ‘man pow’ gives details of the
     values in a large number of corner cases.

     Arithmetic on type double in R is supposed to be done in ‘round to
     nearest, ties to even’ mode, but this does depend on the compiler
     and FPU being set up correctly.

_V_a_l_u_e:

     Unary ‘+’ and unary ‘-’ return a numeric or complex vector.  All
     attributes (including class) are preserved if there is no
     coercion: logical ‘x’ is coerced to integer and names, dims and
     dimnames are preserved.

     The binary operators return vectors containing the result of the
     element by element operations.  If involving a zero-length vector
     the result has length zero.  Otherwise, the elements of shorter
     vectors are recycled as necessary (with a ‘warning’ when they are
     recycled only _fractionally_).  The operators are ‘+’ for
     addition, ‘-’ for subtraction, ‘*’ for multiplication, ‘/’ for
     division and ‘^’ for exponentiation.

     ‘%%’ indicates ‘x mod y’ (“x modulo y”), i.e., computes the
     ‘remainder’ ‘r <- x %% y’, and ‘%/%’ indicates integer division,
     where R uses “floored” integer division, i.e., ‘q <- x %/% y :=
     floor(x/y)’, as promoted by Donald Knuth, see the Wikipedia page
     on ‘Modulo operation’, and hence ‘sign(r) == sign(y)’.  It is
     guaranteed that

     ‘ x == (x %% y) + y * (x %/% y) ’ (up to rounding error)

     unless ‘y == 0’ where the result of ‘%%’ is ‘NA_integer_’ or ‘NaN’
     (depending on the ‘typeof’ of the arguments) or for some
     non-finite arguments, e.g., when the RHS of the identity above
     amounts to ‘Inf - Inf’.

     If either argument is complex the result will be complex,
     otherwise if one or both arguments are numeric, the result will be
     numeric.  If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).

     The rules for determining the attributes of the result are rather
     complicated.  Most attributes are taken from the longer argument.
     Names will be copied from the first if it is the same length as
     the answer, otherwise from the second if that is.  If the
     arguments are the same length, attributes will be copied from
     both, with those of the first argument taking precedence when the
     same attribute is present in both arguments. For time series,
     these operations are allowed only if the series are compatible,
     when the class and ‘tsp’ attribute of whichever is a time series
     (the same, if both are) are used.  For arrays (and an array
     result) the dimensions and dimnames are taken from first argument
     if it is an array, otherwise the second.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Arith’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’ (with ‘e2’ missing for a unary operator).

_I_m_p_l_e_m_e_n_t_a_t_i_o_n _l_i_m_i_t_s:

     R is dependent on OS services (and they on FPUs) for
     floating-point arithmetic.  On all current R platforms IEC 60559
     (also known as IEEE 754) arithmetic is used, but some things in
     those standards are optional.  In particular, the support for
     _denormal_ aka _subnormal_ numbers (those outside the range given
     by ‘.Machine’) may differ between platforms and even between
     calculations on a single platform.

     Another potential issue is signed zeroes: on IEC 60559 platforms
     there are two zeroes with internal representations differing by
     sign.  Where possible R treats them as the same, but for example
     direct output from C code often does not do so and may output
     ‘-0.0’ (and on Windows whether it does so or not depends on the
     version of Windows).  One place in R where the difference might be
     seen is in division by zero: ‘1/x’ is ‘Inf’ or ‘-Inf’ depending on
     the sign of zero ‘x’.  Another place is ‘identical(0, -0, num.eq =
     FALSE)’.

_N_o_t_e:

     All logical operations involving a zero-length vector have a
     zero-length result.

     The binary operators are sometimes called as functions as e.g.
     ‘`&`(x, y)’: see the description of how argument-matching is done
     in ‘Ops’.

     ‘**’ is translated in the parser to ‘^’, but this was undocumented
     for many years.  It appears as an index entry in Becker et al.
     (1988), pointing to the help for ‘Deprecated’ but is not actually
     mentioned on that page.  Even though it had been deprecated in S
     for 20 years, it was still accepted in R in 2008.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     D. Goldberg (1991).  What Every Computer Scientist Should Know
     about Floating-Point Arithmetic.  _ACM Computing Surveys_,
     *23*(1), 5-48.  doi:10.1145/103162.103163
     <https://doi.org/10.1145/103162.103163>.

     Also available at
     <https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html>.

     For the IEC 60559 (aka IEEE 754) standard:
     <https://www.iso.org/standard/57469.html> and
     <https://en.wikipedia.org/wiki/IEEE_754>.

     On the integer division and remainder (modulo) computations, ‘%%’
     and ‘%/%’: <https://en.wikipedia.org/wiki/Modulo_operation>, and
     Donald Knuth (1972) _The Art of Computer Programming_, Vol.1.

_S_e_e _A_l_s_o:

     ‘sqrt’ for miscellaneous and ‘Special’ for special mathematical
     functions.

     ‘Syntax’ for operator precedence.

     ‘%*%’ for matrix multiplication.

_E_x_a_m_p_l_e_s:

     x <- -1:12
     x + 1
     2 * x + 3
     x %%  3 # is periodic  2 0  1  2 0  1 ...
     x %% -3 #  (ditto)    -1 0 -2 -1 0 -2 ...
     x %/% 5
     x %% Inf # now is defined by limit (gave NaN in earlier versions of R)

     ## Illustrating PR#18677, see above
     1 %/% print(0.2, digits=19)

It would appear the backticks are also effective:

In [19]:
?`^`

Arithmetic                package:base                 R Documentation

_A_r_i_t_h_m_e_t_i_c _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     These unary and binary operators perform arithmetic on numeric or
     complex vectors (or objects which can be coerced to them).

_U_s_a_g_e:

     + x
     - x
     x + y
     x - y
     x * y
     x / y
     x ^ y
     x %% y
     x %/% y

_A_r_g_u_m_e_n_t_s:

    x, y: numeric or complex vectors or objects which can be coerced to
          such, or other objects for which methods have been written.

_D_e_t_a_i_l_s:

     The unary and binary arithmetic operators are generic functions:
     methods can be written for them individually or via the ‘Ops’
     group generic function.  (See ‘Ops’ for how dispatch is computed.)

     If applied to arrays the result will be an array if this is
     sensible (for example it will not if the recycling rule has been
     invoked).

     Logical vectors will be coerced to integer or numeric vectors,
     ‘FALSE’ having value zero and ‘TRUE’ having value one.

     ‘1 ^ y’ and ‘y ^ 0’ are ‘1’, _always_.  ‘x ^ y’ should also give
     the proper limit result when either (numeric) argument is infinite
     (one of ‘Inf’ or ‘-Inf’).

     Objects such as arrays or time-series can be operated on this way
     provided they are conformable.

     For double arguments, ‘%%’ can be subject to catastrophic loss of
     accuracy if ‘x’ is much larger than ‘y’, and a warning is given if
     this is detected.

     ‘%%’ and ‘x %/% y’ can be used for non-integer ‘y’, e.g. ‘1 %/%
     0.2’, but the results are subject to representation error and so
     may be platform-dependent.  Mathematically, the answer to ‘1 %/%
     0.2’ should be ‘5’, but because the IEC 60559 representation of
     ‘0.2’ is a binary fraction slightly larger than ‘0.2’ most
     platforms give ‘4’.

     Users are sometimes surprised by the value returned, for example
     why ‘(-8)^(1/3)’ is ‘NaN’.  For double inputs, R makes use of IEC
     60559 arithmetic on all platforms, together with the C system
     function ‘pow’ for the ‘^’ operator.  The relevant standards
     define the result in many corner cases.  In particular, the result
     in the example above is mandated by the C99 standard.  On many
     Unix-alike systems the command ‘man pow’ gives details of the
     values in a large number of corner cases.

     Arithmetic on type double in R is supposed to be done in ‘round to
     nearest, ties to even’ mode, but this does depend on the compiler
     and FPU being set up correctly.

_V_a_l_u_e:

     Unary ‘+’ and unary ‘-’ return a numeric or complex vector.  All
     attributes (including class) are preserved if there is no
     coercion: logical ‘x’ is coerced to integer and names, dims and
     dimnames are preserved.

     The binary operators return vectors containing the result of the
     element by element operations.  If involving a zero-length vector
     the result has length zero.  Otherwise, the elements of shorter
     vectors are recycled as necessary (with a ‘warning’ when they are
     recycled only _fractionally_).  The operators are ‘+’ for
     addition, ‘-’ for subtraction, ‘*’ for multiplication, ‘/’ for
     division and ‘^’ for exponentiation.

     ‘%%’ indicates ‘x mod y’ (“x modulo y”), i.e., computes the
     ‘remainder’ ‘r <- x %% y’, and ‘%/%’ indicates integer division,
     where R uses “floored” integer division, i.e., ‘q <- x %/% y :=
     floor(x/y)’, as promoted by Donald Knuth, see the Wikipedia page
     on ‘Modulo operation’, and hence ‘sign(r) == sign(y)’.  It is
     guaranteed that

     ‘ x == (x %% y) + y * (x %/% y) ’ (up to rounding error)

     unless ‘y == 0’ where the result of ‘%%’ is ‘NA_integer_’ or ‘NaN’
     (depending on the ‘typeof’ of the arguments) or for some
     non-finite arguments, e.g., when the RHS of the identity above
     amounts to ‘Inf - Inf’.

     If either argument is complex the result will be complex,
     otherwise if one or both arguments are numeric, the result will be
     numeric.  If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).

     The rules for determining the attributes of the result are rather
     complicated.  Most attributes are taken from the longer argument.
     Names will be copied from the first if it is the same length as
     the answer, otherwise from the second if that is.  If the
     arguments are the same length, attributes will be copied from
     both, with those of the first argument taking precedence when the
     same attribute is present in both arguments. For time series,
     these operations are allowed only if the series are compatible,
     when the class and ‘tsp’ attribute of whichever is a time series
     (the same, if both are) are used.  For arrays (and an array
     result) the dimensions and dimnames are taken from first argument
     if it is an array, otherwise the second.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Arith’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’ (with ‘e2’ missing for a unary operator).

_I_m_p_l_e_m_e_n_t_a_t_i_o_n _l_i_m_i_t_s:

     R is dependent on OS services (and they on FPUs) for
     floating-point arithmetic.  On all current R platforms IEC 60559
     (also known as IEEE 754) arithmetic is used, but some things in
     those standards are optional.  In particular, the support for
     _denormal_ aka _subnormal_ numbers (those outside the range given
     by ‘.Machine’) may differ between platforms and even between
     calculations on a single platform.

     Another potential issue is signed zeroes: on IEC 60559 platforms
     there are two zeroes with internal representations differing by
     sign.  Where possible R treats them as the same, but for example
     direct output from C code often does not do so and may output
     ‘-0.0’ (and on Windows whether it does so or not depends on the
     version of Windows).  One place in R where the difference might be
     seen is in division by zero: ‘1/x’ is ‘Inf’ or ‘-Inf’ depending on
     the sign of zero ‘x’.  Another place is ‘identical(0, -0, num.eq =
     FALSE)’.

_N_o_t_e:

     All logical operations involving a zero-length vector have a
     zero-length result.

     The binary operators are sometimes called as functions as e.g.
     ‘`&`(x, y)’: see the description of how argument-matching is done
     in ‘Ops’.

     ‘**’ is translated in the parser to ‘^’, but this was undocumented
     for many years.  It appears as an index entry in Becker et al.
     (1988), pointing to the help for ‘Deprecated’ but is not actually
     mentioned on that page.  Even though it had been deprecated in S
     for 20 years, it was still accepted in R in 2008.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     D. Goldberg (1991).  What Every Computer Scientist Should Know
     about Floating-Point Arithmetic.  _ACM Computing Surveys_,
     *23*(1), 5-48.  doi:10.1145/103162.103163
     <https://doi.org/10.1145/103162.103163>.

     Also available at
     <https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html>.

     For the IEC 60559 (aka IEEE 754) standard:
     <https://www.iso.org/standard/57469.html> and
     <https://en.wikipedia.org/wiki/IEEE_754>.

     On the integer division and remainder (modulo) computations, ‘%%’
     and ‘%/%’: <https://en.wikipedia.org/wiki/Modulo_operation>, and
     Donald Knuth (1972) _The Art of Computer Programming_, Vol.1.

_S_e_e _A_l_s_o:

     ‘sqrt’ for miscellaneous and ‘Special’ for special mathematical
     functions.

     ‘Syntax’ for operator precedence.

     ‘%*%’ for matrix multiplication.

_E_x_a_m_p_l_e_s:

     x <- -1:12
     x + 1
     2 * x + 3
     x %%  3 # is periodic  2 0  1  2 0  1 ...
     x %% -3 #  (ditto)    -1 0 -2 -1 0 -2 ...
     x %/% 5
     x %% Inf # now is defined by limit (gave NaN in earlier versions of R)

     ## Illustrating PR#18677, see above
     1 %/% print(0.2, digits=19)

`data()` will show which datasets R has obnoxiously polluted the global namespace with:

In [20]:
data()

Data sets in package ‘datasets’:

AirPassengers           Monthly Airline Passenger Numbers 1949-1960
BJsales                 Sales Data with Leading Indicator
BJsales.lead (BJsales)
                        Sales Data with Leading Indicator
BOD                     Biochemical Oxygen Demand
CO2                     Carbon Dioxide Uptake in Grass Plants
ChickWeight             Weight versus age of chicks on different diets
DNase                   Elisa assay of DNase
EuStockMarkets          Daily Closing Prices of Major European Stock
                        Indices, 1991-1998
Formaldehyde            Determination of Formaldehyde
HairEyeColor            Hair and Eye Color of Statistics Students
Harman23.cor            Harman Example 2.3
Harman74.cor            Harman Example 7.4
Indometh                Pharmacokinetics of Indomethacin
InsectSprays            Effectiveness of Insect Sprays
JohnsonJohnson          Quarterly Earnings per Johnson & Johnson Share
LakeHuron               Level of Lake Huron 1875-1972
LifeCycleSavings        Intercountry Life-Cycle Savings Data
Loblolly                Growth of Loblolly Pine Trees
Nile                    Flow of the River Nile
Orange                  Growth of Orange Trees
OrchardSprays           Potency of Orchard Sprays
PlantGrowth             Results from an Experiment on Plant Growth
Puromycin               Reaction Velocity of an Enzymatic Reaction
Seatbelts               Road Casualties in Great Britain 1969-84
Theoph                  Pharmacokinetics of Theophylline
Titanic                 Survival of passengers on the Titanic
ToothGrowth             The Effect of Vitamin C on Tooth Growth in
                        Guinea Pigs
UCBAdmissions           Student Admissions at UC Berkeley
UKDriverDeaths          Road Casualties in Great Britain 1969-84
UKgas                   UK Quarterly Gas Consumption
USAccDeaths             Accidental Deaths in the US 1973-1978
USArrests               Violent Crime Rates by US State
USJudgeRatings          Lawyers' Ratings of State Judges in the US
                        Superior Court
USPersonalExpenditure   Personal Expenditure Data
UScitiesD               Distances Between European Cities and Between
                        US Cities
VADeaths                Death Rates in Virginia (1940)
WWWusage                Internet Usage per Minute
WorldPhones             The World's Telephones
ability.cov             Ability and Intelligence Tests
airmiles                Passenger Miles on Commercial US Airlines,
                        1937-1960
airquality              New York Air Quality Measurements
anscombe                Anscombe's Quartet of 'Identical' Simple Linear
                        Regressions
attenu                  The Joyner-Boore Attenuation Data
attitude                The Chatterjee-Price Attitude Data
austres                 Quarterly Time Series of the Number of
                        Australian Residents
beaver1 (beavers)       Body Temperature Series of Two Beavers
beaver2 (beavers)       Body Temperature Series of Two Beavers
cars                    Speed and Stopping Distances of Cars
chickwts                Chicken Weights by Feed Type
co2                     Mauna Loa Atmospheric CO2 Concentration
crimtab                 Student's 3000 Criminals Data
discoveries             Yearly Numbers of Important Discoveries
esoph                   Smoking, Alcohol and (O)esophageal Cancer
euro                    Conversion Rates of Euro Currencies
euro.cross (euro)       Conversion Rates of Euro Currencies
eurodist                Distances Between European Cities and Between
                        US Cities
faithful                Old Faithful Geyser Data
fdeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
freeny                  Freeny's Revenue Data
freeny.x (freeny)       Freeny's Revenue Data
freeny.y (freeny)       Freeny's Revenue Data
infert                  Infertility after Spontaneous and Induced
                        Abortion
iris                    Edgar Anderson's Iris Data
iris3                   Edgar Anderson's Iris Data
islands                 Areas of the World's Major Landmasses
ldeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
lh                      Luteinizing Hormone in Blood Samples
longley                 Longley's Economic Regression Data
lynx                    Annual Canadian Lynx trappings 1821-1934
mdeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
morley                  Michelson Speed of Light Data
mtcars                  Motor Trend Car Road Tests
nhtemp                  Average Yearly Temperatures in New Haven
nottem                  Average Monthly Temperatures at Nottingham,
                        1920-1939
npk                     Classical N, P, K Factorial Experiment
occupationalStatus      Occupational Status of Fathers and their Sons
precip                  Annual Precipitation in US Cities
presidents              Quarterly Approval Ratings of US Presidents
pressure                Vapor Pressure of Mercury as a Function of
                        Temperature
quakes                  Locations of Earthquakes off Fiji
randu                   Random Numbers from Congruential Generator
                        RANDU
rivers                  Lengths of Major North American Rivers
rock                    Measurements on Petroleum Rock Samples
sleep                   Student's Sleep Data
stack.loss (stackloss)
                        Brownlee's Stack Loss Plant Data
stack.x (stackloss)     Brownlee's Stack Loss Plant Data
stackloss               Brownlee's Stack Loss Plant Data
state.abb (state)       US State Facts and Figures
state.area (state)      US State Facts and Figures
state.center (state)    US State Facts and Figures
state.division (state)
                        US State Facts and Figures
state.name (state)      US State Facts and Figures
state.region (state)    US State Facts and Figures
state.x77 (state)       US State Facts and Figures
sunspot.month           Monthly Sunspot Data, from 1749 to "Present"
sunspot.year            Yearly Sunspot Data, 1700-1988
sunspots                Monthly Sunspot Numbers, 1749-1983
swiss                   Swiss Fertility and Socioeconomic Indicators
                        (1888) Data
treering                Yearly Tree-Ring Data, -6000-1979
trees                   Diameter, Height and Volume for Black Cherry
                        Trees
uspop                   Populations Recorded by the US Census
volcano                 Topographic Information on Auckland's Maunga
                        Whau Volcano
warpbreaks              The Number of Breaks in Yarn during Weaving
women                   Average Heights and Weights for American Women

Use ‘data(package = .packages(all.available = TRUE))’
to list the data sets in all *available* packages.

Here is `co2`, for instance:

In [21]:
co2

     Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct
1959 315.42 316.31 316.50 317.56 318.13 318.00 316.39 314.65 313.68 313.18
1960 316.27 316.81 317.42 318.87 319.87 319.43 318.01 315.74 314.00 313.68
1961 316.73 317.54 318.38 319.31 320.42 319.61 318.42 316.63 314.83 315.16
1962 317.78 318.40 319.53 320.42 320.85 320.45 319.45 317.25 316.11 315.27
1963 318.58 318.92 319.70 321.22 322.08 321.31 319.58 317.61 316.05 315.83
1964 319.41 320.07 320.74 321.40 322.06 321.73 320.27 318.54 316.54 316.71
1965 319.27 320.28 320.73 321.97 322.00 321.71 321.05 318.71 317.66 317.14
1966 320.46 321.43 322.23 323.54 323.91 323.59 322.24 320.20 318.48 317.94
1967 322.17 322.34 322.88 324.25 324.83 323.93 322.38 320.76 319.10 319.24
1968 322.40 322.99 323.73 324.86 325.40 325.20 323.98 321.95 320.18 320.09
1969 323.83 324.26 325.47 326.50 327.21 326.54 325.72 323.50 322.22 321.62
1970 324.89 325.82 326.77 327.97 327.91 327.50 326.18 324.53 322.93 322.90
1971 326.01 326.51 327.01 327.62 328.76 328.40 327.20 325.27 323.20 323.40
1972 326.60 327.47 327.58 329.56 329.90 328.92 327.88 326.16 324.68 325.04
1973 328.37 329.40 330.14 331.33 332.31 331.90 330.70 329.15 327.35 327.02
1974 329.18 330.55 331.32 332.48 332.92 332.08 331.01 329.23 327.27 327.21
1975 330.23 331.25 331.87 333.14 333.80 333.43 331.73 329.90 328.40 328.17
1976 331.58 332.39 333.33 334.41 334.71 334.17 332.89 330.77 329.14 328.78
1977 332.75 333.24 334.53 335.90 336.57 336.10 334.76 332.59 331.42 330.98
1978 334.80 335.22 336.47 337.59 337.84 337.72 336.37 334.51 332.60 332.38
1979 336.05 336.59 337.79 338.71 339.30 339.12 337.56 335.92 333.75 333.70
1980 337.84 338.19 339.91 340.60 341.29 341.00 339.39 337.43 335.72 335.84
1981 339.06 340.30 341.21 342.33 342.74 342.08 340.32 338.26 336.52 336.68
1982 340.57 341.44 342.53 343.39 343.96 343.18 341.88 339.65 337.81 337.69
1983 341.20 342.35 342.93 344.77 345.58 345.14 343.81 342.21 339.69 339.82
1984 343.52 344.33 345.11 346.88 347.25 346.62 345.22 343.11 340.90 341.18
1985 344.79 345.82 347.25 348.17 348.74 348.07 346.38 344.51 342.92 342.62
1986 346.11 346.78 347.68 349.37 350.03 349.37 347.76 345.73 344.68 343.99
1987 347.84 348.29 349.23 350.80 351.66 351.07 349.33 347.92 346.27 346.18
1988 350.25 351.54 352.05 353.41 354.04 353.62 352.22 350.27 348.55 348.72
1989 352.60 352.92 353.53 355.26 355.52 354.97 353.75 351.52 349.64 349.83
1990 353.50 354.55 355.23 356.04 357.00 356.07 354.67 352.76 350.82 351.04
1991 354.59 355.63 357.03 358.48 359.22 358.12 356.06 353.92 352.05 352.11
1992 355.88 356.63 357.72 359.07 359.58 359.17 356.94 354.92 352.94 353.23
1993 356.63 357.10 358.32 359.41 360.23 359.55 357.53 355.48 353.67 353.95
1994 358.34 358.89 359.95 361.25 361.67 360.94 359.55 357.49 355.84 356.00
1995 359.98 361.03 361.66 363.48 363.82 363.30 361.94 359.50 358.11 357.80
1996 362.09 363.29 364.06 364.76 365.45 365.01 363.70 361.54 359.51 359.65
1997 363.23 364.06 364.61 366.40 366.84 365.68 364.52 362.57 360.24 360.83
     Nov    Dec
1959 314.66 315.43
1960 314.84 316.03
1961 315.94 316.85
1962 316.53 317.53
1963 316.91 318.20
1964 317.53 318.55
1965 318.70 319.25
1966 319.63 320.87
1967 320.56 321.80
1968 321.16 322.74
1969 322.69 323.95
1970 323.85 324.96
1971 324.63 325.85
1972 326.34 327.39
1973 327.99 328.48
1974 328.29 329.41
1975 329.32 330.59
1976 330.14 331.52
1977 332.24 333.68
1978 333.75 334.78
1979 335.12 336.56
1980 336.93 338.04
1981 338.19 339.44
1982 339.09 340.32
1983 340.98 342.82
1984 342.80 344.04
1985 344.06 345.38
1986 345.48 346.72
1987 347.64 348.78
1988 349.91 351.18
1989 351.14 352.37
1990 352.69 354.07
1991 353.64 354.89
1992 354.09 355.33
1993 355.30 356.78
1994 357.59 359.05
1995 359.61 360.74
1996 360.80 362.38
1997 362.49 364.34

Here are the class and type of `co2`, respectively:

In [22]:
class(co2)
typeof(co2)

[1] "ts"

[1] "double"

R features the mathematical constants $\pi$ and negative and positive $\infty$:

In [23]:
pi
-Inf
Inf

[1] 3.141593

[1] -Inf

[1] Inf

One can also get $e$ this way:

In [24]:
exp(1)

[1] 2.718282

Let's see how close R's base facilities can come to Euler's identity, $e^{i\pi} + 1 = 0$:

In [25]:
exp(sqrt(as.complex(-1)) * pi) + 1

[1] 0+1.224647e-16i

The result is indeed very close (but not identical) to 0.

The book later says not to save your workspace if you're using the R shell or RStudio. Just noting that here. Now for a few exercises.

**Exercise 1**: What is the sum of the first 100 positive integers? The formula for the sum of integers 1 through $n$ is $\frac{n(n+1)}{2}$. Define $n = 100$ and then use R to compute the sum of 1 through 100 using the formula. What is the sum?

I'll do a little better than that.

In [26]:
sum_of_positive_integers_from_1_to <- function(n) {
    n * (n + 1) / 2
}

sum_of_positive_integers_from_1_to(100)

[1] 5050

**Exercise 2**: Now use the same formula to compute the sum of the integers from 1 through 1000.

In [27]:
sum_of_positive_integers_from_1_to(1000)

[1] 500500

**Exercise 3**: Look at the result of typing the following code into R:

```r
n <- 1000
x <- seq(1, n)
sum(x)
```

Based on the result, what do you think the functions `seq()` and `sum()` do? You can use `help()`.

1. `sum()` creates a list of numbers and `seq()` adds them up.
2. `seq()` creates a list of numbers and `sum()` adds them up.
3. `seq()` creates a random list and `sum` computes the sum of 1 through 1,000.
4. `sum()` always returns the same number.

The answer is obviously #2.

**Exercise 4**: In math and programming, we say that we evaluate a function when we replace the argument with a given value. So if we type `sqrt(4)`, we evaluate the `sqrt()` function. In R, you can evaluate a function inside another function. The evaluations happen from the inside out. Use one line of code to compute the log, in base 10, of the square root of 100.

Easy; in fact I'll do a little better than that:

In [28]:
sqrt(100) |> log(base=10)

[1] 1

**Exercise 5**: Which of the following will always return the numeric value stored in `x`? You can try out examples and use the help system if you want.

1. `log(10^x)`
2. `log10(x^10)`
3. `log(exp(x))`
4. `exp(log(x, base = 2))`

Also easy:

In [29]:
seq(1, 100) |> exp() |> log()

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100